/run/numberOfThreads 40
/run/initialize

# ---- GPS (fissi) ----
/gps/particle e-
/gps/pos/centre 0 0 -2 m
/gps/pos/type Beam
/gps/pos/sigma_x 1 mm
/gps/pos/sigma_y 1 mm
/gps/ang/type beam2d
/gps/ang/rot1 1  0  0
/gps/ang/rot2 0 -1  0
/gps/ang/sigma_x 147.73E-6 rad
/gps/ang/sigma_y 161.60E-6 rad

# ---- Scan energia: 10, 12.5, 15, 17.5, 20, 22.5, 25 GeV ----
/control/loop ../one_energy.mac E 32 60 2 
